locals {
  common_tags = {
    project     = var.project_name
    environment = var.environment
    owner       = var.owner
    cost_center = var.cost_center
    managed_by  = "terraform"
  }

  environment_path = "${path.module}/${var.output_root}/${var.environment}"
}

resource "local_file" "app_config" {
  filename = "${local.environment_path}/config.json"
  content = jsonencode({
    project     = var.project_name
    environment = var.environment
    tags        = local.common_tags
    created_by  = "terraform-local-example"
  })
}

resource "local_file" "deployment_manifest" {
  filename = "${local.environment_path}/deployment.yaml"
  content  = <<-YAML
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${var.project_name}-${var.environment}
      labels:
        app: ${var.project_name}
        environment: ${var.environment}
        managed-by: terraform
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${var.project_name}
          environment: ${var.environment}
      template:
        metadata:
          labels:
            app: ${var.project_name}
            environment: ${var.environment}
            owner: ${var.owner}
            cost-center: ${var.cost_center}
        spec:
          containers:
            - name: app
              image: ${var.project_name}:${var.environment}
              ports:
                - containerPort: 3000
  YAML
}

resource "local_file" "readme" {
  filename = "${local.environment_path}/README.txt"
  content  = <<-TEXT
    Generated by Terraform local provider example.

    Project: ${var.project_name}
    Environment: ${var.environment}
    Owner: ${var.owner}
    Cost center: ${var.cost_center}

    This folder simulates infrastructure artifacts without creating cloud resources.
  TEXT
}
