apiVersion: v1
kind: Service
metadata:
  name: docker-example
  namespace: docker-example
  labels:
    app: docker-example
    app.kubernetes.io/name: docker-example
    app.kubernetes.io/part-of: devops-starter-kit
spec:
  type: ClusterIP
  selector:
    app: docker-example
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
